server:
  port: 8080

spring:
  application:
    name: cachey
  data:
    redis:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          test-on-borrow: true
          test-while-idle: true
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.cachey: INFO
    org.springframework.data.redis: DEBUG